// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	userV1 "github.com/fivezjd/go_zero_how/internal/handler/userV1"
	userV2 "github.com/fivezjd/go_zero_how/internal/handler/userV2"
	"github.com/fivezjd/go_zero_how/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: userV1.Go_zero_howHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: userV1.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: userV2.UserRegisterV2Handler(serverCtx),
			},
		},
		rest.WithPrefix("/v2"),
	)
}
